# Generated by Django 3.2.7 on 2021-09-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('language', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Service_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.provider')),
            ],
        ),
    ]
